### ISSUE TITLE
Should put "log" and "ckpt_LEARNER_DATE_TIME" into same folder?

### ISSUE THREAD

**Issue by pengzhenghao** [opendilab/DI-engine#1]
<img width="432" alt="image" src="https://user-images.githubusercontent.com/22206995/124722467-aa1d2280-df3c-11eb-8bcc-37f4ffd4a921.png">

Now the checkpoints and log data are stored in two separate folders. Should we introduce a higher level folder, name EXPERIMENT_NAME or so to store all data of single experiment in it?

By the way, the name format of the checkpoint look quite weird to me, why there are two "_" between the date? I suggest to make it as "checkpoints_MODELNAME" and this is enough! It is not reasonable to write the "created time" in the folder name, since the folder contains lots of checkpoints that are created at different time.

**Comment by PaParaZz1** [comment]
How about the following output file structure:
- users need to indicate the field `experiment_name` in user config, just like:
  ```python
  main_config = dict(
      experiment_name='test_exp_name',
      policy=dict(
          ...,
      ),
      env=dict(
          ...,
      ),
  )
  ```
  and if this field is not indicated, engine will set this value in the following default format——'exp_createtime'
- In a high level experiment folder, the specific output contents can be like this:
  <img width="456" alt="Screen Shot 2021-07-09 at 4 20 37 PM" src="https://user-images.githubusercontent.com/33195032/125047704-d027fb80-e0d1-11eb-88a4-cf633782ec05.png">

**Comment by HansBug** [comment]
Well, this problem is actually the relation between run log and checkpoint data.

You can analysis like this:

* If you need to keep the every-time running log, and it is usually can related one by one with a checkpoint, then you should just put them together.
* If every-time running log is not necessary (or too big to keep, too complex so that not able to manage it, any reasons like these), just keep the current structure.

So just think about the user need, the answer is there.

**Comment by PaParaZz1** [comment]
this issue has been figured out in PR #10
