### ISSUE TITLE
CPU utilization problem

### ISSUE THREAD

**Issue by zxzzz0** [opendilab/DI-engine#102]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] system worker bug
    + [x] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc]()
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
```python
  # ding version `v0.2.0`, linux platform
```

### Issue Description
CPU utilization is not 100% and very low. (below 5% on average)

### Steps to Reproduce 
clone the repo and `git checkout main`. (currently on `0fcfdf26`).  Run `python3 dizoo/slime_volley/entry/slime_volley_selfplay_ppo_main.py`. Open `htop` to check CPU usage. Only one core is occupied on a multi-core machine.

### What Do We Need?
During training, run command `mpstat 3`. The column of `%idle` is less than `20%` (Current value is `97%`)

**Comment by zxzzz0** [comment]
Hello, this is a serious system design problem, which may require fundamental refactor of the framework. Need some guys familiar with framework and system design to work on this. 

Could us know the current progress on this? @PaParaZz1

**Comment by PaParaZz1** [comment]
> Hello, this is a serious system design problem, which may require fundamental refactor of the framework. Need some guys familiar with framework and system design to work on this.
> 
> Could us know the current progress on this? @PaParaZz1

We are preparing new design about main entry function and new benchmark results on cartpole will be updated at 11.8.

**Comment by zxzzz0** [comment]
> ...will be updated at 11.8.

@PaParaZz1, could us know the latest FPS results? Do we get as fast as SampleFactory

**Comment by zxzzz0** [comment]
One open source framework released last week showed that [EnvPool](https://envpool.readthedocs.io/en/latest/pages/benchmark.html) can get even 2x improvement over SampleFactory. 

@PaParaZz1  Could us know the latest FPS results of di-engine please 😔

**Comment by PaParaZz1** [comment]
> One open source framework released last week showed that [EnvPool](https://envpool.readthedocs.io/en/latest/pages/benchmark.html) can get even 2x improvement over SampleFactory.
> 
> @PaParaZz1 Could us know the latest FPS results of di-engine please 😔

`EnvPool` is `cpp env manager` what I said before, and we are doing a new brave main entry refactor, so we delay the detailed asynchronous pipeline benchmark to the end of November. Besides, we will adapt a new env manager choice(DI-engine + EnvPool) this week, but `EnvPool` only supports Atari now.

**Comment by zxzzz0** [comment]
@PaParaZz1 Hello there, it's been 3 months long. We have to ask if there is any update on this ticket.

**Comment by sailxjx** [comment]
Hi, @zxzzz0, glad to see you are still following about this issue. In fact, we have been making some important improvements in the past three months, including process architecture optimization and objective horizontal comparison. First, please take a look at some of the results of our test:

<img width="581" alt="Screen Shot 2022-01-28 at 18 11 07" src="https://user-images.githubusercontent.com/909853/151528621-5c2ea1b4-ce62-4b0a-aa47-f7da45957889.png">

All test code, reports and tensorboard screenshots will be open sourced on github in the future, so you can try it yourself.

Next I will try to explain the problems you found and our solution (and will be updated in 1.0 version). 

RL efficiency is divided into two parts: environment collection speed and training speed, and we are concerned with maximizing the overall speed, because if the environment is constantly collected (using the entire CPU) and the training speed cannot keep up, it will only cause a large amount of invalid data. ,vice versa.

Therefore, we mainly solve this problem from two aspects. The first is to make the collection and training asynchronous, so that the model will not wait for the data of the environment, and the environment will not wait for the model to update, and the two can maintain a certain step difference. In fact, not only the environment and training, most of the steps within the entire pipeline can be asynchronous. This is not well supported in most frameworks as far as I know.

The second point is to reduce the waste of resources caused by the synchronization of the parent and child processes, that is what you said, the problem of CPU running dissatisfaction during collection. In fact, if you use the top command, the env manager does not always run down the CPU of the entire machine, but there will be periodic fluctuations in it. This fluctuation is due to the fact that only one parent process is used to collect all of the data in child processes. We will solve this issue of bottleneck in v1.0, and we can see the difference in cpu usage between the new execution mode (bottom of picture) and the previous execution mode (top of picture) through the upper and lower comparison charts.

<img width="760" alt="Screen Shot 2022-01-28 at 18 30 21" src="https://user-images.githubusercontent.com/909853/151531534-b5a39b35-94d7-4249-bb6e-5a3a72f83ed4.png">

I hope these explanations will restore your confidence in DI-engine and help you in your future work, keep following us, thank you.

Best.
