### ISSUE TITLE
Can you provide a complete example of environment migration?

### ISSUE THREAD

**Issue by lxxxsd** [opendilab/DI-engine#264]
Can you provide a complete example of environment migration? I can't move into my environment.

**Comment by uuid0000** [comment]
See here [gfootball_env.py](https://github.com/opendilab/DI-engine/tree/13c3c9c2cb476cae70671fa568fb2fb7098ccfc5/dizoo/gfootball) this is an example of the `gfootball` environment migration. See the upper `dizoo/gfootball/` level for file structures.

In fact, every module in the [dizoo](https://github.com/opendilab/DI-engine/tree/13c3c9c2cb476cae70671fa568fb2fb7098ccfc5/dizoo) level is an example of customized environment migration.

Think of scripts here [ding/envs/env/](https://github.com/opendilab/DI-engine/tree/main/ding/envs/env) as template files for env migration. All the modules under [dizoo](https://github.com/opendilab/DI-engine/tree/13c3c9c2cb476cae70671fa568fb2fb7098ccfc5/dizoo) directory have customized these template files (an `xxx_env.py`, (sometimes with) an `xxx_wrapper.py`, and (sometimes with) an entry `__init__.py`). 

You can try to imitate any of these modules (I recommend this [dizoo/slime_volley/envs/slime_volley_env.py](https://github.com/opendilab/DI-engine/blob/main/dizoo/slime_volley/envs/slime_volley_env.py) if your environment is more divergent and more complex/customized than what had been included in `ding`, because some of the gym modules in ding have pre-programmed wrappers that saved a lot of customization efforts, but if your environment has a similar variant that's already included in `ding` then feel free to use the corresponding wrapper to make life easier.

**Comment by PaParaZz1** [comment]
> Can you provide a complete example of environment migration? I can't move into my environment.

ok, we will add a more specific example about how to transform a general decision-making problem into DI-engine's RL environment after current holiday. And you can refer to the examples in dizoo first.

**Comment by lxxxsd** [comment]
Thank you very much. I'm learning how to do it!

**Comment by PaParaZz1** [comment]
You can refer to our new doc about `how to migrate your own RL env` [English](https://di-engine-docs.readthedocs.io/en/latest/04_best_practice/ding_env.html) | [中文](https://di-engine-docs.readthedocs.io/zh_CN/latest/04_best_practice/ding_env_zh.html) .

And we will also add a series of doc about `how to define your decision problem into a RL env` in August.
