### ISSUE TITLE
Is it a bug about transformer mask?

### ISSUE THREAD

**Issue by ppeterpp** [opendilab/DI-engine#333]
https://github.com/opendilab/DI-engine/blob/3bf01a9212c0b4a1a4d0877884941d5ad70630cd/ding/torch_utils/network/transformer.py#L72

I suppose it was meant to be an in place func here, masked_fill_() to be exact, otherwise maybe it wouldn't work

**Comment by PaParaZz1** [comment]
It is indeed a mistake. We have fixed it and add corresponding unittest in this [commit](https://github.com/opendilab/DI-engine/commit/dc064896e164cae1061db8b1ffe7cd084a0aed1f). 

For existing algorithm (e.g. GTrXL), we don't use variable-length input coupled with mask so that it will not cause performance degradation.
