### ISSUE TITLE
r2d2 atari

### ISSUE THREAD

**Issue by hlsafin** [opendilab/DI-engine#403]
Hello there, I'm sort of a newbie here. I am trying to reproduce some of the atari games with R2D2, and I am unable to produce them. I've been blocked on this for quite some time and it would be a great help if anyone can help me here. 
Thank you.

**Comment by davide97l** [comment]
Hello @hlsafin, first of all you should make sure to train your agent for enough training steps in order to see meaningful results. For example, using our default configuration, R2D2 takes about 4M steps to converge on Pong and 10M to reach good performance on Spaceinvaders. Moreover, there are two important h-paramerers you may want to tune for different environments:
- burnin_step: how many steps to use for initializing RNN hidden state, since those steps are not used for training, you could reduce them in those envs where initial steps are the most important.
- learn_unroll_len: length of a trajectory, you could increase this value when having a longer memory is critical.

You can refer to this file to see all the h-parameters that can be tuned: https://github.com/opendilab/DI-engine/blob/main/dizoo/atari/config/serial/pong/pong_r2d2_config.py

Following, I'm going to attach our training log relative to the Pong environment so that you can make a comparison.
![image](https://user-images.githubusercontent.com/41103541/176608785-cc26a18f-8dc2-4b70-a4aa-87938d0678f0.png)

**Comment by hlsafin** [comment]
![image](https://user-images.githubusercontent.com/36808133/176976452-ef958dc5-e863-4879-a3eb-adb4361941df.png)
Yeah, that's so weird, I am running the same file as you, but getting different results. Hmm

**Comment by hlsafin** [comment]
at 2.4 million, the mean reward is still around -20

**Comment by PaParaZz1** [comment]
can you upload your tensorboard event?

**Comment by hlsafin** [comment]
yeah, I don't think I can upload files here. Maybe I can email you? I tried oppo_config, and it converged. Just no luck with r2d2 config.py

**Comment by hlsafin** [comment]
yeah, I can't seem to find it. When you ran your config, did you make any changes to the config file? Also, which version are you using?

**Comment by PaParaZz1** [comment]
slack channel link: https://join.slack.com/t/opendilab/shared_invite/zt-v9tmv4fp-nUBAQEH1_Kuyu_q4plBssQ
