### ISSUE TITLE
DI gym_anytrading reward and profit functions are wrong..?

### ISSUE THREAD

**Issue by HaakonFlaaronning** [opendilab/DI-engine#569]
In https://github.com/opendilab/DI-engine/tree/main/dizoo/gym_anytrading/envs the profit and reward function logic is all wrong..?

![image](https://user-images.githubusercontent.com/57355918/211191465-e9f43cc1-4f56-4bef-af7d-40c32ac4023e.png)

In the profit calculation you would have to multiply the profit from long trades with that of short trades (not add them together).

Also, reward for long would be:

log((close_curr / close_pre) * cost) - wouldn't it?

And for short:

log((close_pre / close_curr) * cost) ?

Am I wrong here or does the current logic not make any sense? Also, what is the reason for taking the natural logarithm? Why not keep reward as (close_curr / close_pre) * cost for long and (close_pre / close_curr) * cost) for short?

**Comment by Cloud-Pku** [comment]
1.Indeed, it's right to multiply the profit from long trades with that of short trades. Thank you for your correction, we will make modifications.
2.For the calculation of short selling, imagine two timestamps t1 and t2:
The closing price is close1 at time t1 and close2 at time t2.
At t1, agent has capital M in hand, it can borrow M/close1 stock from the broker and sell it, and it needs to buy M/close1 stock at t2 to pay back the broker. The net profit of agent from t1 to t2 is $\frac{M}{close1} * close1 - \frac{M}{close1} * close2$, 
and the yield rate is (net profit + M)/M, so for short:
$\frac{\frac{M}{close1} * close1 - \frac{M}{close1} * close2 + M}{M} = 2 - close2/close1$
3.The effect of natural logarithm is to transform multiplication into accumulation. The optimal goal of reinforcement learning is to maximize cumulative reward. We set reward = log(profit), so that maximizing $\Sigma reward$ is equivalent to maximizing $\prod profit$
